version: '3.8'

services:
  classics-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classics-web:v1.0.0
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - VITE_API_URL=https://classics-api.zzszyct.xyz/
    ports:
      - "25531:3000"
    restart: unless-stopped
