version: '3.8'

services:
  classics-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classics-web
    env_file:
      - .env
    ports:
      - "25531:3000"
    restart: unless-stopped
